In [1]:
import pandas as pd

In [2]:
pip install kagglehub

Requirement already satisfied: kagglehub in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.3.4)
Requirement already satisfied: packaging in /Users/luckyc/Library/Python/3.13/lib/python/site-packages (from kagglehub) (24.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("CooperUnion/anime-recommendations-database")

print("Path to dataset files:", path)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.5)
Path to dataset files: /Users/luckyc/.cache/kagglehub/datasets/CooperUnion/anime-recommendations-database/versions/1

In [4]:
import numpy as np

In [5]:
#get the anime dataset

anime_data = pd.read_csv("anime.csv")

In [6]:
#get rating dataset
anime_rating = pd.read_csv("rating.csv")

In [7]:
#number of rows and columns in anime dataset
data_shape = anime_data.shape
print(f" The DataFrame has {data_shape[0]} rows and {data_shape[1]} columns! \n")
print(anime_data.info())

 The DataFrame has 12294 rows and 7 columns!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB
None

In [8]:
#number of rows and colums in rating dataset
rating_shape = anime_rating.shape
print(f" The DataFrame has {rating_shape[0]} rows and {rating_shape[1]} columns! \n")
print(anime_rating.info())

 The DataFrame has 7813737 rows and 3 columns!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB
None

In [9]:
#top 5 rows 
anime_data.head(5)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [10]:
#last 5 rows
anime_data.tail(5)

,anime_id,name,genre,type,episodes,rating,members
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [11]:
# checking min of rating column in anime data dataset
anime_data_min = anime_data["rating"].min()
print(f"The minimum in the anime data dataset for the Rating column is {anime_data_min}")

The minimum in the anime data dataset for the Rating column is 1.67

In [12]:
# checking min of rating column in anime data dataset
anime_data_max = anime_data["rating"].max()
print(f"The maximum in the anime data dataset for the Rating column is {anime_data_max}")

The maximum in the anime data dataset for the Rating column is 10.0

In [13]:
#top 5 rows of rating
anime_rating.head(5)

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [14]:
#last 5 rows of rating
anime_rating.tail(5)

         user_id  anime_id  rating
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

In [15]:
# checking min of rating column in anime rating dataset
anime_rating_min = anime_rating["rating"].min()
print(f"The minimum in the anime rating dataset for the Rating column is {anime_rating_min}")

The minimum in the anime rating dataset for the Rating column is -1

In [16]:
#checking max of rating column in anime rating dataset
anime_rating_max = anime_rating["rating"].max()
print(f"The maximum in the anime rating dataset for the Rating column is {anime_rating_max}")

The maximum in the anime rating dataset for the Rating column is 10

In [17]:
#checking for null, empty for data
null_anime = anime_data.isnull()
print(null_anime)

       anime_id   name  genre   type  episodes  rating  members
0         False  False  False  False     False   False    False
1         False  False  False  False     False   False    False
2         False  False  False  False     False   False    False
3         False  False  False  False     False   False    False
4         False  False  False  False     False   False    False
...         ...    ...    ...    ...       ...     ...      ...
12289     False  False  False  False     False   False    False
12290     False  False  False  False     False   False    False
12291     False  False  False  False     False   False    False
12292     False  False  False  False     False   False    False
12293     False  False  False  False     False   False    False

[12294 rows x 7 columns]

In [18]:
#checking for null, empty for rating
null_rating = anime_rating.isnull()
print(null_rating)

         user_id  anime_id  rating
0          False     False   False
1          False     False   False
2          False     False   False
3          False     False   False
4          False     False   False
...          ...       ...     ...
7813732    False     False   False
7813733    False     False   False
7813734    False     False   False
7813735    False     False   False
7813736    False     False   False

[7813737 rows x 3 columns]

In [19]:
# checking if any values are null in data of anime data
print(anime_data.isnull().any().any())

True

In [20]:
# Getting a count of null values in each column
anime_data.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [21]:
anime_data.isnull().any(axis=0)

anime_id    False
name        False
genre        True
type         True
episodes    False
rating       True
members     False
dtype: bool

In [22]:
#Displays only rows that contain null values

anime_data[anime_data.isna().any(axis=1)]

,anime_id,name,genre,type,episodes,rating,members
2844,33242,IS: Infinite Stratos 2 - Infinite Wedding,NaN,Special,1,7.15,6604
3541,33589,ViVid Strike!,NaN,TV,12,6.96,12345
6040,29765,Metropolis (2009),NaN,Movie,1,6.27,313
6646,32695,Match Shoujo,NaN,ONA,1,6.02,242
7018,33187,Katsudou Shashin,NaN,Movie,1,5.79,607
...,...,...,...,...,...,...,...
12274,34492,Nuki Doki! Tenshi to Akuma no Sakusei Battle -...,Hentai,OVA,Unknown,NaN,392
12279,34491,Sagurare Otome The Animation,Hentai,OVA,1,NaN,79
12280,34312,Saimin Class,Hentai,OVA,Unknown,NaN,240
12282,34388,Shikkoku no Shaga The Animation,Hentai,OVA,Unknown,NaN,195
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

In [23]:
#Identify Empty rows/columns
anime_data.info

<bound method DataFrame.info of        anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
...         ...                                                ...
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami
12290      5543                                        Under World
12291      5621                     Violence Gekiga David no Hoshi
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...
12293     26081                   Yasuji no Pornorama: Yacchimae!!

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
3                                       Sci-Fi, Thriller     TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
...                                                  ...    ...      ...
12289                                             Hentai    OVA        1
12290                                             Hentai    OVA        1
12291                                             Hentai    OVA        4
12292                                             Hentai    OVA        1
12293                                             Hentai  Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
...       ...      ...
12289    4.15      211
12290    4.28      183
12291    4.88      219
12292    4.98      175
12293    5.46      142

[12294 rows x 7 columns]>

In [24]:
#Column names for anime data
anime_data.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [25]:
#using describe for anime data
pd.options.display.float_format = "{:,.2f}".format
anime_data.describe()

       anime_id    rating      members
count 12,294.00 12,064.00    12,294.00
mean  14,058.22      6.47    18,071.34
std   11,455.29      1.03    54,820.68
min        1.00      1.67         5.00
25%    3,484.25      5.88       225.00
50%   10,260.50      6.57     1,550.00
75%   24,794.50      7.18     9,437.00
max   34,527.00     10.00 1,013,917.00

In [26]:
# checking if any values are null in data of anime rating
print(anime_rating.isnull().any().any())

False

In [27]:
anime_rating.isnull().any(axis=0)

user_id     False
anime_id    False
rating      False
dtype: bool

In [28]:
#column names for anime rating
anime_rating.columns

Index(['user_id', 'anime_id', 'rating'], dtype='object')

In [29]:
#using describe for anime rating
pd.options.display.float_format = "{:,.2f}".format
anime_rating.describe()

           user_id     anime_id       rating
count 7,813,737.00 7,813,737.00 7,813,737.00
mean     36,727.96     8,909.07         6.14
std      20,997.95     8,883.95         3.73
min           1.00         1.00        -1.00
25%      18,974.00     1,240.00         6.00
50%      36,791.00     6,213.00         7.00
75%      54,757.00    14,093.00         9.00
max      73,516.00    34,519.00        10.00

In [30]:
#convert data columns to title case
anime_data.columns = anime_data.columns.str.title()
anime_data.head(2)

,Anime_Id,Name,Genre,Type,Episodes,Rating,Members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665

In [31]:
#convert rating columns to title case
anime_rating.columns = anime_rating.columns.str.title()
anime_rating.head(2)

   User_Id  Anime_Id  Rating
0        1        20      -1
1        1        24      -1

In [32]:
columns_to_drop = ["Episodes", "Members"]

In [33]:
anime_data_drop = anime_data.drop(columns = columns_to_drop)

anime_data_drop.head(2)

,Anime_Id,Name,Genre,Type,Rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,9.26

In [34]:
anime_data_clean = anime_data.dropna(how= "any")
anime_data_clean

,Anime_Id,Name,Genre,Type,Episodes,Rating,Members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [35]:
#displays any nulls that may have not been cleaned. if clean is proper it should be blank

anime_data_clean[anime_data_clean.isna().any(axis=1)]

Empty DataFrame
Columns: [Anime_Id, Name, Genre, Type, Episodes, Rating, Members]
Index: []

In [36]:
anime_data_clean.head(5)

,Anime_Id,Name,Genre,Type,Episodes,Rating,Members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [37]:
anime_data_clean.tail(5)

,Anime_Id,Name,Genre,Type,Episodes,Rating,Members
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [38]:
anime_data_clean.describe()

       Anime_Id    Rating      Members
count 12,017.00 12,017.00    12,017.00
mean  13,638.00      6.48    18,348.88
std   11,231.08      1.02    55,372.50
min        1.00      1.67        12.00
25%    3,391.00      5.89       225.00
50%    9,959.00      6.57     1,552.00
75%   23,729.00      7.18     9,588.00
max   34,519.00     10.00 1,013,917.00

In [39]:
anime_data_clean.shape

(12017, 7)

In [40]:
def filter_by_name(anime_data_clean, search_term):
    # use str.contains() for partial match
    return anime_data_clean[anime_data_clean["Name"].str.contains(search_term, case=False)]

In [41]:
filter_by_name(anime_data_clean, "Death Note")

,Anime_Id,Name,Genre,Type,Episodes,Rating,Members
40,1535,Death Note,"Mystery, Police, Psychological, Supernatural, ...",TV,37,8.71,1013917
778,2994,Death Note Rewrite,"Mystery, Police, Psychological, Supernatural, ...",Special,2,7.84,88699

In [42]:
#This is the rating information for the anime_data dataset which has a column for rating

def summarize_anime_data(anime_data_clean: anime_data) -> str:
    """
    Calculates and summarizes the total, mean, and median number of Rating in 
    Anime dataset.

    Parameters:
        anime_data (pandas.DataFrame): The anime dataset containing a 
                                         'Rating' column.

    Returns:
        str: A formatted string summarizing the total, mean (rounded to 2 decimal places),
             and median number of ratings.
    """
    # Calculate total, mean, and median backers
    anime_data_rating_sum = anime_data_clean['Rating'].sum()
    anime_data_rating_mean = anime_data_clean['Rating'].mean().round(2)
    anime_data_rating_median = anime_data_clean['Rating'].median()

    # Return a formatted string
    return (f"The total number of Ratings is {anime_data_rating_sum}\n"
            f"The mean number of Ratings is {anime_data_rating_mean}\n"
            f"The median number of Ratings is {anime_data_rating_median}")

In [43]:
#This is the summary of anime_data rating (sum, mean and median)
summary_anime_data = summarize_anime_data(anime_data_clean)
print(summary_anime_data)

The total number of Ratings is 77849.3
The mean number of Ratings is 6.48
The median number of Ratings is 6.57

In [44]:
#This is the rating information for the anime_rating dataset which also has a rating column
def summarize_anime_rating(anime_rating) -> str:
    """
    Calculates and summarizes the total, mean, and median number of Rating in 
    Anime rating dataset.

    Parameters:
        anime_data (pandas.DataFrame): The anime rating dataset containing a 
                                         'Rating' column.

    Returns:
        str: A formatted string summarizing the total, mean (rounded to 2 decimal places),
             and median number of ratings.
    """
    # Calculate total, mean, and median backers
    anime_rating_sum = anime_rating['Rating'].sum()
    anime_rating_mean = anime_rating['Rating'].mean().round(2)
    anime_rating_median = anime_rating['Rating'].median()

    # Return a formatted string
    return (f"The total number of Ratings is {anime_rating_sum}\n"
            f"The mean number of Ratings is {anime_rating_mean}\n"
            f"The median number of Ratings is {anime_rating_median}")

In [45]:
#This is the summary of anime_rating dataset ratings (sum, mean, median)
#summary_anime_rating = summarize_anime_rating(anime_rating)
#print(summary_anime_rating)

In [46]:
#Attempt to merge dataframes anime_data_clean and anime_rating 
merged_anime = pd.merge(anime_data_clean, anime_rating, on='Anime_Id', how='inner')

In [47]:
merged_anime.shape

(7813611, 9)

In [48]:
#Checking top view
merged_anime.head()

,Anime_Id,Name,Genre,Type,Episodes,Rating_x,Members,User_Id,Rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1

In [49]:
#Checking bottom view

merged_anime.tail()

,Anime_Id,Name,Genre,Type,Episodes,Rating_x,Members,User_Id,Rating_y
7813606,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,39532,-1
7813607,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,48766,-1
7813608,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4
7813609,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,27364,-1
7813610,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,48766,-1

In [50]:
#group by Anime Id Name and Rating_y called grouped_
#grouped = merged_anime.groupby(["Anime_Id", "Name", "Type"])

In [51]:
#grouped by mean of rating
##grouped_mean = merged_anime.groupby(["Anime_Id", "Name", "Type"])["Rating_y"].mean()

In [52]:
#grouped_mean_df = grouped_mean.reset_index()

In [53]:
#display grouped mean of Anime_Id and Name by Rating Mean
#grouped_mean_df.shape

In [54]:
#sorted_group_mean = grouped_mean_df.sort_values(by="Rating_y", ascending=False)
#sorted_group_mean.head(5)

In [55]:
#Create a function for sorting by type
#def sorted_columns(grouped_mean_df, search_value):
    # Filter based on search_value in "Type" column
   # filtered_df = grouped_mean_df[grouped_mean_df["Type"].str.contains(search_value, case=False)]
    
    # Sort the filtered dataframe by "Rating_y" highest to lowest
  #  sorted_df = filtered_df.sort_values(by="Rating_y", ascending=False)
    
   # return sorted_df

In [56]:
#Unique values in column "Type"
#unique_types = grouped_mean_df['Type'].unique()
#print(unique_types)

In [57]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'
#sorted_type_tv = sorted_columns(grouped_mean_df, "TV")

#sorted_type_tv.head(5)

In [58]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'

#sorted_type_movie = sorted_columns(grouped_mean_df, "Movie")

#sorted_type_movie.head(5)

In [59]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'

#sorted_type_ova = sorted_columns(grouped_mean_df, "OVA")

#sorted_type_ova.head(5)

In [60]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'

#sorted_type_special = sorted_columns(grouped_mean_df, "Special")

#sorted_type_special.head(5)

In [61]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'

#sorted_type_ona = sorted_columns(grouped_mean_df, "ona")

#sorted_type_ona.head(5)

In [62]:
#Top 50 for 'TV 'Movie 'OVA' 'Special' 'ONA' 'Music'

#sorted_type_music = sorted_columns(grouped_mean_df, "Music")

#sorted_type_music.head(5)

In [63]:
# Filter the DataFrame for successful projects
filtered_data = merged_anime[merged_anime['Rating_y'] >= 7.5]

# Group by Category and State and sum the specified columns
top_anime = filtered_data.groupby(['Anime_Id', 'Name', 'Type'])[[ 'Rating_y']].mean().reset_index()

# Sort the entire DataFrame by 'Usd Pledged Real' in descending order
top_anime = top_anime.sort_values(by='Rating_y', ascending=False)

top_anime.shape

(8262, 4)

In [64]:
def sorted_columns(top_anime, search_value):
    #Filter based on search_value in "Type" column
    filtered_top_anime = top_anime[top_anime["Type"].str.contains(search_value, case=False)]
    
    # Sort the filtered dataframe by "Rating_y" highest to lowest
    sorted_top_anime = filtered_top_anime.sort_values(by="Rating_y", ascending=False)
    
    return sorted_top_anime

In [73]:
top_anime_tv= sorted_columns(top_anime, "TV")

In [74]:
top_anime_tv.head()

      Anime_Id                               Name Type  Rating_y
7130     23349             Kirin Monoshiri Yakata   TV     10.00
2324      2575               Don Chuck Monogatari   TV     10.00
4822      8353                           Ketsuinu   TV     10.00
6454     17291      Jinzou Konchuu Kabutoborg VxV   TV     10.00
4836      8375  Chogattai Majutsu Robot Ginguiser   TV     10.00

In [65]:
top_anime = top_anime.sort_values(by=["Rating_y"], ascending=[False])
top_anime.head(25)

,Anime_Id,Name,Type,Rating_y
7217,24139,Tokyo Babylon: Vision,Music,10.00
5446,10520,Nurse Witch Komugi-chan Magikarte Z Special,Special,10.00
7030,22479,Hello Kitty no Mahou no Ringo,OVA,10.00
2775,3155,Kingyo Chuuihou! (Movie),Movie,10.00
7130,23349,Kirin Monoshiri Yakata,TV,10.00
7029,22477,Hello Kitty no Tomatta Big Ben,OVA,10.00
6370,16604,Pinky,ONA,10.00
6371,16606,C.L.A.Y.,ONA,10.00
2806,3214,Kosuke-sama Rikimaru-sama: Konpeitou no Ryuu,OVA,10.00
3986,5609,Emi to Yobanaide,OVA,10.00
2847,3277,Kinnikuman: Haresugata! Seigi Choujin,Movie,10.00
2848,3278,Kinnikuman: New York Kiki Ippatsu!,Movie,10.00
2849,3279,Kinnikuman: Seigi Choujin vs. Senshi Choujin,Movie,10.00
2850,3280,Kinnikuman: Kessen! Shichinin no Seigi Choujin...,Special,10.00
7981,31747,Oshiri Kajiri Mushi (TV) 4th Season,TV,10.00
3443,4331,Penguin no Mondai,TV,10.00
6238,15545,Oshiri Kajiri Mushi (TV),TV,10.00
4253,6383,Chargeman Ken!,TV,10.00
7955,31634,Kokuhaku,ONA,10.00
7942,31568,Wake Up,Music,10.00
3197,3838,Himitsu no Akko-chan 2,TV,10.00
3160,3769,Play Ball 2nd,TV,10.00
2846,3276,Kinnikuman: Gyakushuu! Uchuu Kakure Choujin,Movie,10.00
5265,9990,Midori-ko,Movie,10.00
7025,22441,Hello Kitty: Ringo no Mori to Parallel Town,TV,10.00

In [66]:
top_anime_sorted = sorted_columns(grouped_mean, search_value)

NameError: name 'grouped_mean' is not defined

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter


# 1. Top 25 Anime by Rating_y
plt.figure(figsize=(10, 6))
top_pledged = top_ten_cats.groupby('Category')['Usd Pledged Real'].sum().nlargest(10)

# Highlight the highest value in blue, others in light grey
colors = ['blue' if i == 0 else 'lightgrey' for i in range(len(top_pledged))]

plt.bar(top_pledged.index, top_pledged.values, color=colors)

# Add value only on the blue bar (the highest one)
plt.text(0, top_pledged.values[0], f'{top_pledged.values[0]:,.0f}', 
         ha='center', va='bottom', fontsize=12, color='black')

# Formatting for x-axis labels and title
plt.xticks(rotation=45, ha='right')
plt.title('Top 10 Categories by Total Pledged Amount')
plt.xlabel('Category')
plt.ylabel('Total Pledged Amount (USD)')

# Add comma formatting for y-axis
plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.tight_layout()
plt.show()

# 2. Top 25 Anime by Rating_y with Type TV
#plt.figure(figsize=(10, 6))
#top_backers = top_ten_cats.groupby('Category')['Backers'].sum().nlargest(10)

# Highlight the highest value in blue, others in light grey
#colors = ['blue' if i == 0 else 'lightgrey' for i in range(len(top_backers))]

#plt.bar(top_backers.index, top_backers.values, color=colors)

# Add value only on the blue bar (the highest one)
#plt.text(0, top_backers.values[0], f'{top_backers.values[0]:,.0f}', 
        # ha='center', va='bottom', fontsize=12, color='black')

# Formatting for x-axis labels and title
#plt.xticks(rotation=45, ha='right')
#plt.title('Top 10 Categories by Number of Backers')
#plt.xlabel('Category')
#plt.ylabel('Number of Backers')

# Add comma formatting for y-axis
#plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda x, _: f'{x:,.0f}'))
#plt.tight_layout()
#plt.show()

NameError: name 'top_ten_cats' is not defined

In [ ]:
#checking for duplicate User_Id
#duplicates = merged_anime.duplicated(subset='Anime_Id')
#print(duplicates)

In [ ]:
#checking for duplicate User_Id
#duplicates_sum = merged_anime.duplicated(subset='User_Id').sum()
#print(duplicates_sum)

In [ ]:
#Creating copy of merged
#merged_anime_copy= merged_anime.copy()

In [ ]:
#dropping duplicates in copy for merged_anime
#merged_anime_copy = merged_anime_copy.drop_duplicates(subset=['User_Id'])

In [ ]:
#merged_anime_copy.shape

In [ ]:
#merged_anime_copy.head()

In [ ]:
#checking for any null values
#merged_anime.isnull().any().any()

np.False_

In [ ]:
#Checking values

#def summarize_merged_anime_x(merged_anime: anime_data_clean) -> str:
    #"""
    #Calculates and summarizes the total, mean, and median number of Rating in 
    #Merged Anime dataset.

    #Parameters:
        #merged_anime (pandas.DataFrame): The anime dataset containing a 
         #                                'Rating' column.

  #  Returns:
   #     str: A formatted string summarizing the total, mean (rounded to 2 decimal places),
    #         and median number of ratings.
   # """
    # Calculate total, mean, and median backers
   # merged_anime_sum_x= merged_anime["Rating_x"].sum().round(2)
    #merged_anime_mean_x = merged_anime["Rating_x"].mean().round(2)
   # merged_anime_median_x = merged_anime["Rating_x"].median()

    # Return a formatted string
    #return (f"The total number of Ratings is {merged_anime_sum_x}\n"
     #       f"The mean number of Ratings is {merged_anime_mean_x}\n"
      #      f"The median number of Ratings is {merged_anime_median_x}")

In [ ]:
#This is the summary of anime_rating dataset ratings (sum, mean, median)
#summary_merged_anime_x = summarize_merged_anime_x(merged_anime)
#print(summary_merged_anime_x)

In [ ]:
#Checking values

#def summarize_merged_anime_y(merged_anime: anime_rating) -> str:
 #   """
  #  Calculates and summarizes the total, mean, and median number of Rating in 
   # Merged Anime dataset.

  #  Parameters:
   #     merged_anime (pandas.DataFrame): The anime dataset containing a 
    #                                     'Rating' column.

  #  Returns:
   #     str: A formatted string summarizing the total, mean (rounded to 2 decimal places),
    #         and median number of ratings.
   # """
    # Calculate total, mean, and median backers
    #merged_anime_sum_y= merged_anime["Rating_y"].sum().round(2)
    #merged_anime_mean_y = merged_anime["Rating_y"].mean().round(2)
    #merged_anime_median_y = merged_anime["Rating_y"].median()

    # Return a formatted string
   # return (f"The total number of Ratings is {merged_anime_sum_y}\n"
    #        f"The mean number of Ratings is {merged_anime_mean_y}\n"
     #       f"The median number of Ratings is {merged_anime_median_y}")

In [ ]:
#This is the summary of anime_rating dataset ratings (sum, mean, median)
#summary_merged_anime_y = summarize_merged_anime_y(merged_anime)
#print(summary_merged_anime_y)